/* Generated by Yosys 0.9+4052 (git sha1 d061b0e, gcc 8.3.1 -fPIC -Os) */

module dvsd_pe(in, en, out, eno, gs);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  input en;
  output eno;
  output gs;
  input [7:0] in;
  output [2:0] out;
  sky130_fd_sc_hd__buf_1 _28_ (
    .A(in[5]),
    .X(_01_)
  );
  sky130_fd_sc_hd__buf_1 _29_ (
    .A(in[4]),
    .X(_02_)
  );
  sky130_fd_sc_hd__inv_2 _30_ (
    .A(in[7]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__buf_1 _31_ (
    .A(in[6]),
    .X(_04_)
  );
  sky130_fd_sc_hd__inv_2 _32_ (
    .A(in[6]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o22a_2 _33_ (
    .A1(_03_),
    .A2(_04_),
    .B1(in[7]),
    .B2(_05_),
    .X(_06_)
  );
  sky130_fd_sc_hd__or3_2 _34_ (
    .A(_01_),
    .B(_02_),
    .C(_06_),
    .X(_07_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _35_ (
    .A1_N(_01_),
    .A2_N(_02_),
    .B1(in[5]),
    .B2(in[4]),
    .X(_08_)
  );
  sky130_fd_sc_hd__or3_2 _36_ (
    .A(in[7]),
    .B(_04_),
    .C(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__buf_1 _37_ (
    .A(in[3]),
    .X(_10_)
  );
  sky130_fd_sc_hd__or2_2 _38_ (
    .A(in[1]),
    .B(in[0]),
    .X(_11_)
  );
  sky130_fd_sc_hd__or3_2 _39_ (
    .A(_10_),
    .B(in[2]),
    .C(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__a21oi_2 _40_ (
    .A1(_07_),
    .A2(_09_),
    .B1(_12_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__inv_2 _41_ (
    .A(in[2]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _42_ (
    .A1_N(_10_),
    .A2_N(_13_),
    .B1(in[3]),
    .B2(_13_),
    .X(_14_)
  );
  sky130_fd_sc_hd__or2_2 _43_ (
    .A(_11_),
    .B(_14_),
    .X(_15_)
  );
  sky130_fd_sc_hd__inv_2 _44_ (
    .A(_11_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a2111o_2 _45_ (
    .A1(in[1]),
    .A2(in[0]),
    .B1(_10_),
    .C1(in[2]),
    .D1(_16_),
    .X(_17_)
  );
  sky130_fd_sc_hd__or4_2 _46_ (
    .A(_01_),
    .B(_02_),
    .C(in[7]),
    .D(_04_),
    .X(_18_)
  );
  sky130_fd_sc_hd__a21oi_2 _47_ (
    .A1(_15_),
    .A2(_17_),
    .B1(_18_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__o21ai_2 _48_ (
    .A1(_27_),
    .A2(_19_),
    .B1(en),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2_2 _49_ (
    .A(in[0]),
    .B(en),
    .Y(eno)
  );
  sky130_fd_sc_hd__or4b_2 _50_ (
    .A(in[7]),
    .B(_04_),
    .C(_02_),
    .D_N(_01_),
    .X(_20_)
  );
  sky130_fd_sc_hd__o41a_2 _51_ (
    .A1(_01_),
    .A2(_02_),
    .A3(_03_),
    .A4(_04_),
    .B1(_20_),
    .X(_21_)
  );
  sky130_fd_sc_hd__inv_2 _52_ (
    .A(in[1]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__or3b_2 _53_ (
    .A(_11_),
    .B(in[2]),
    .C_N(_10_),
    .X(_23_)
  );
  sky130_fd_sc_hd__o41a_2 _54_ (
    .A1(_10_),
    .A2(in[2]),
    .A3(_22_),
    .A4(in[0]),
    .B1(_23_),
    .X(_24_)
  );
  sky130_fd_sc_hd__o22ai_2 _55_ (
    .A1(_12_),
    .A2(_21_),
    .B1(_18_),
    .B2(_24_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__o22ai_2 _56_ (
    .A1(_12_),
    .A2(_07_),
    .B1(_18_),
    .B2(_15_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__inv_2 _57_ (
    .A(eno),
    .Y(gs)
  );
  sky130_fd_sc_hd__dlxtn_1 _58_ (
    .D(_25_),
    .GATE_N(_00_),
    .Q(out[0])
  );
  sky130_fd_sc_hd__dlxtn_1 _59_ (
    .D(_26_),
    .GATE_N(_00_),
    .Q(out[1])
  );
  sky130_fd_sc_hd__dlxtn_1 _60_ (
    .D(_27_),
    .GATE_N(_00_),
    .Q(out[2])
  );
endmodule
